packages:
  - apps/*
  - packages/*
  - packages/modules/*
autoInstallPeers: false
allowBuilds:
  '@prisma/engines@7.9.1': true
  'prisma@7.9.1': true
  unrs-resolver: true
blockExoticSubdeps: true
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
saveExact: true
sharedWorkspaceLockfile: true
strictDepBuilds: true
strictPeerDependencies: true
